# Generated by Django 4.0.3 on 2022-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='employee_id',
            field=models.CharField(default='', max_length=240, null=True),
        ),
    ]
